# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='document',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
