# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0004_auto_20161214_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='document',
            field=models.FileField(upload_to='cf/static/cf/documents/'),
        ),
    ]
