# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0007_auto_20161214_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='document',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
    ]
